version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: mt-postgres
    environment:
      POSTGRES_USER: mtuser
      POSTGRES_PASSWORD: mtpassword
      POSTGRES_DB: mt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mt-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: